[server]
headless = true
enableCORS = false
port = $PORT

[theme]
base = "dark"
primaryColor = "#00c7ec"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"
